// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CountDown.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Countdown {
  public static partial class CountDownService
  {
    static readonly string __ServiceName = "countdown.CountDownService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Countdown.ClientCountDownRequest> __Marshaller_countdown_ClientCountDownRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Countdown.ClientCountDownRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Countdown.ClientCountDownResponse> __Marshaller_countdown_ClientCountDownResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Countdown.ClientCountDownResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Countdown.ServerCountDownRequest> __Marshaller_countdown_ServerCountDownRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Countdown.ServerCountDownRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Countdown.ServerCountDownResponse> __Marshaller_countdown_ServerCountDownResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Countdown.ServerCountDownResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Countdown.ClientCountDownRequest, global::Countdown.ClientCountDownResponse> __Method_StartClientCountDown = new grpc::Method<global::Countdown.ClientCountDownRequest, global::Countdown.ClientCountDownResponse>(
        grpc::MethodType.ClientStreaming,
        __ServiceName,
        "StartClientCountDown",
        __Marshaller_countdown_ClientCountDownRequest,
        __Marshaller_countdown_ClientCountDownResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Countdown.ServerCountDownRequest, global::Countdown.ServerCountDownResponse> __Method_StartServerCountDown = new grpc::Method<global::Countdown.ServerCountDownRequest, global::Countdown.ServerCountDownResponse>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "StartServerCountDown",
        __Marshaller_countdown_ServerCountDownRequest,
        __Marshaller_countdown_ServerCountDownResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Countdown.CountDownReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of CountDownService</summary>
    [grpc::BindServiceMethod(typeof(CountDownService), "BindService")]
    public abstract partial class CountDownServiceBase
    {
      /// <summary>
      /// Client starts and sends coundown, Server replies when count down reaches the end
      /// </summary>
      /// <param name="requestStream">Used for reading requests from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Countdown.ClientCountDownResponse> StartClientCountDown(grpc::IAsyncStreamReader<global::Countdown.ClientCountDownRequest> requestStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Client sends amount of Seconds to coundown, Server starts a countdown from the specified number of seconds
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="responseStream">Used for sending responses back to the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>A task indicating completion of the handler.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task StartServerCountDown(global::Countdown.ServerCountDownRequest request, grpc::IServerStreamWriter<global::Countdown.ServerCountDownResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(CountDownServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_StartClientCountDown, serviceImpl.StartClientCountDown)
          .AddMethod(__Method_StartServerCountDown, serviceImpl.StartServerCountDown).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, CountDownServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_StartClientCountDown, serviceImpl == null ? null : new grpc::ClientStreamingServerMethod<global::Countdown.ClientCountDownRequest, global::Countdown.ClientCountDownResponse>(serviceImpl.StartClientCountDown));
      serviceBinder.AddMethod(__Method_StartServerCountDown, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::Countdown.ServerCountDownRequest, global::Countdown.ServerCountDownResponse>(serviceImpl.StartServerCountDown));
    }

  }
}
#endregion
